use std::fs;

use camino::Utf8Path;
use serde::Deserialize;
use serde_json::{Map, Value};

use crate::{RuntimeConfig, infra::http::build_blocking_http_client};

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct ImportBucket {
    #[serde(rename = "Name", alias = "name")]
    pub name: String,
    #[serde(rename = "Source", alias = "source")]
    pub source: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct ImportApp {
    #[serde(rename = "Info", alias = "info", default)]
    pub info: String,
    #[serde(rename = "Name", alias = "name")]
    pub name: String,
    #[serde(rename = "Source", alias = "source", default)]
    pub source: String,
    #[serde(rename = "Version", alias = "version")]
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct ImportScoopfile {
    #[serde(default)]
    pub config: Map<String, Value>,
    #[serde(default)]
    pub buckets: Vec<ImportBucket>,
    #[serde(default)]
    pub apps: Vec<ImportApp>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImportAppPlan {
    pub name: String,
    pub app_reference: String,
    pub global: bool,
    pub architecture: Option<String>,
    pub hold: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ImportLoadError {
    InvalidJson,
    LocalJsonParse { path: String },
}

pub fn load_import_scoopfile(
    _config: &RuntimeConfig,
    source: &str,
) -> Result<ImportScoopfile, ImportLoadError> {
    if Utf8Path::new(source).exists() {
        let contents = fs::read_to_string(source).map_err(|_| ImportLoadError::LocalJsonParse {
            path: source.to_owned(),
        })?;
        return serde_json::from_str(&contents).map_err(|_| ImportLoadError::LocalJsonParse {
            path: source.to_owned(),
        });
    }
    if looks_like_remote_source(source) {
        let client = build_blocking_http_client().map_err(|_| ImportLoadError::InvalidJson)?;
        let response = client
            .get(source)
            .send()
            .and_then(|response| response.error_for_status())
            .map_err(|_| ImportLoadError::InvalidJson)?;
        let contents = response.text().map_err(|_| ImportLoadError::InvalidJson)?;
        return serde_json::from_str(&contents).map_err(|_| ImportLoadError::InvalidJson);
    }
    Err(ImportLoadError::InvalidJson)
}

pub fn build_import_plan(scoopfile: &ImportScoopfile) -> Vec<ImportAppPlan> {
    let imported_bucket_names = scoopfile
        .buckets
        .iter()
        .map(|bucket| bucket.name.as_str())
        .collect::<Vec<_>>();

    scoopfile
        .apps
        .iter()
        .map(|app| {
            let info = split_info(&app.info);
            let architecture = imported_architecture(&info);
            let global = info.contains(&"Global install");
            let hold = info.contains(&"Held package");
            let app_reference = if imported_bucket_names.contains(&app.source.as_str()) {
                format!("{}/{}", app.source, app.name)
            } else if app.source == "<auto-generated>" {
                format!("{}@{}", app.name, app.version)
            } else {
                app.source.clone()
            };
            ImportAppPlan {
                name: app.name.clone(),
                app_reference,
                global,
                architecture,
                hold,
            }
        })
        .collect()
}

fn split_info(info: &str) -> Vec<&str> {
    if info.is_empty() {
        Vec::new()
    } else {
        info.split(", ").collect()
    }
}

fn imported_architecture(info: &[&str]) -> Option<String> {
    let default_architecture = default_architecture();
    ["64bit", "32bit", "arm64"]
        .into_iter()
        .find(|architecture| info.contains(architecture) && *architecture != default_architecture)
        .map(str::to_owned)
}

fn default_architecture() -> &'static str {
    match std::env::consts::ARCH {
        "x86_64" => "64bit",
        "aarch64" => "arm64",
        _ => "32bit",
    }
}

fn looks_like_remote_source(source: &str) -> bool {
    source.starts_with("http://") || source.starts_with("https://") || source.starts_with("\\\\")
}

#[cfg(test)]
mod tests {
    use std::fs;

    use camino::Utf8PathBuf;
    use serde_json::json;
    use tempfile::TempDir;

    use crate::RuntimeConfig;

    use super::{ImportLoadError, build_import_plan, load_import_scoopfile};

    #[test]
    fn loads_local_scoopfile_json() {
        let fixture = Fixture::new();
        let path = fixture.local_root.join("scoopfile.json");
        fs::write(
            &path,
            json!({
                "buckets": [{"Name":"main","Source":"https://example.invalid/main"}],
                "apps": [{"Name":"demo","Version":"1.0.0","Source":"main","Info":"Held package"}]
            })
            .to_string(),
        )
        .expect("scoopfile should be written");

        let loaded =
            load_import_scoopfile(&fixture.config(), path.as_str()).expect("scoopfile should load");

        assert_eq!(loaded.buckets.len(), 1);
        assert_eq!(loaded.apps.len(), 1);
        assert_eq!(loaded.apps[0].name, "demo");
    }

    #[test]
    fn reports_local_parse_failures_separately() {
        let fixture = Fixture::new();
        let path = fixture.local_root.join("bad.json");
        fs::write(&path, "{bad").expect("invalid json should be written");

        let error = load_import_scoopfile(&fixture.config(), path.as_str())
            .expect_err("invalid json should fail");

        assert_eq!(
            error,
            ImportLoadError::LocalJsonParse {
                path: path.to_string(),
            }
        );
    }

    #[test]
    fn derives_install_and_hold_plan_from_exported_rows() {
        let scoopfile = serde_json::from_value(json!({
            "buckets": [{"Name":"main","Source":"https://example.invalid/main"}],
            "apps": [
                {"Name":"demo","Version":"1.0.0","Source":"main","Info":"Held package"},
                {"Name":"manual","Version":"2.0.0","Source":"<auto-generated>","Info":"Global install, 32bit"}
            ]
        }))
        .expect("scoopfile should deserialize");

        let plan = build_import_plan(&scoopfile);

        assert_eq!(plan[0].app_reference, "main/demo");
        assert!(plan[0].hold);
        assert_eq!(plan[1].app_reference, "manual@2.0.0");
        assert!(plan[1].global);
    }

    struct Fixture {
        _temp: TempDir,
        local_root: Utf8PathBuf,
        global_root: Utf8PathBuf,
    }

    impl Fixture {
        fn new() -> Self {
            let temp = TempDir::new().expect("temp dir should be created");
            let root = Utf8PathBuf::from_path_buf(temp.path().to_path_buf())
                .expect("temp path should be valid UTF-8");
            let local_root = root.join("local");
            let global_root = root.join("global");
            fs::create_dir_all(&local_root).expect("local root should exist");
            fs::create_dir_all(&global_root).expect("global root should exist");
            Self {
                _temp: temp,
                local_root,
                global_root,
            }
        }

        fn config(&self) -> RuntimeConfig {
            RuntimeConfig::new(self.local_root.clone(), self.global_root.clone())
        }
    }
}
